apiVersion: v1
kind: Service
metadata:
  name: autopilot-app-svc
  namespace: autopilot-ops
spec:
  type: NodePort
  selector:
    app: autopilot-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
